name: Macos 14 ARM64 Build

on: [ workflow_dispatch ]

jobs:
  macos-arm64-build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          include:
            - os: macos-14
              arch: arm64
              job_name: "macos 14 ARM64 Build"
              
      steps:
      - uses: actions/checkout@v2  
      - name: Install dependencies
        run: |
          brew install cmake gcc boost
      
      - name: Clone and build LightGBM
        run: |
          git clone --recursive https://github.com/microsoft/LightGBM
          cd LightGBM
          mkdir build
          cd build
          cmake -DUSE_OPENMP=OFF -DBUILD_STATIC_LIB=ON ..
          make -j4

      - name: Verify c_api.h exists in LightGBM
        run: |
          FILE=/Users/runner/work/luna-base/luna-base/LightGBM/include/LightGBM/c_api.h
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
          else
            echo "$FILE does not exist."
            exit 1  # Causes the workflow to fail if the file does not exist
          fi
          
      - name: Build FFTW
        run: |
          wget http://www.fftw.org/fftw-3.3.10.tar.gz
          tar -xzvf fftw-3.3.10.tar.gz
          cd fftw-3.3.10
          ./configure --prefix=$HOME/fftw-3.3.10 CFLAGS="-arch arm64"
          make
          make install
    
      - name: Final Build
        run: |
          make ARCH=MAC LGBM=1 LGBM_PATH=$HOME/LightGBM FFTW=$HOME/fftw-3.3.10
          ref='refs/tags/v'
          if [[ ${{ github.ref }} == *${ref}* ]]; then
            v=$(echo ${{ github.ref }} | cut -d'/' -f3)
            mkdir luna-${v}
            cp luna destrat behead luna-${v}/
            cd luna-${v}/
            otool -L ./luna
            cd ..
            tar cvzf macos-arm64-luna.tar.gz luna-${v}/
          fi
    
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: macos-arm64-binary
          path: macos-arm64-luna.tar.gz
